- group:    Traits
  start:    11-10-2023 19:30
  deadline: 25-10-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: p-stack
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/pstack
    - task: flatmap
      score: 200
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/flatmap

- group:    Traits
  start:    04-10-2023 12:00
  deadline: 18-10-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: trust
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/trust

- group:    Slices & enums
  start:    27-09-2023 19:30
  deadline: 11-10-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: ini
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/ini
    - task: polka
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/polka

- group:    Fun
  start:    20-09-2023 19:30
  deadline: 04-10-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: paperio
      score: 300
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/paperio

- group:    Starters
  start:    13-09-2023 19:30
  deadline: 27-09-2023 19:30
  second_deadline: 31-01-2024 23:59
  enabled: true
  tasks:
    - task: comm
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/comm
    - task: perc
      score: 100
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/perc

- group:    Test
  start:    01-09-2023 18:00
  deadline: 31-12-2023 23:59
  enabled: true
  tasks:
    - task: add
      score: 0
      url: https://gitlab.manytask.org/rust-ysda/public-2023-fall/-/tree/master/add
