[workspace]
members = [
    # Tasks
    "add",
    "comm",
    "perc",
    "paperio",
    "ini",
    "polka",
    "trust",

    # Tools
    "tools/submit",
    "paperio/tools/wasm-launcher",
]
resolver = "2"
